name: Update Extension on Stores
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    name: Build ${{ matrix.build_target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_target:
          - chromium
          - firefox
    steps:
      - uses: actions/checkout@v3.5.3
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build:${{ matrix.build_target }}
        env:
          UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
      - uses: actions/upload-artifact@v3
        with:
          name: tab-nine-${{ matrix.build_target }}
          path: dist/${{ matrix.build_target }}
  upload-chrome-store:
    needs: [build]
    name: Upload extension to Chrome Store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: tab-nine-chromium
      - run: zip release.zip ./* -r
      - run: npm install -g chrome-webstore-upload-cli
      - run: chrome-webstore-upload upload --source release.zip --extension-id ${{ secrets.CHROME_EXTENSION_ID }} --client-id ${{ secrets.CI_GOOGLE_CLIENT_ID }} --client-secret ${{ secrets.CI_GOOGLE_CLIENT_SECRET }} --refresh-token ${{ secrets.CI_GOOGLE_REFRESH_TOKEN }} --auto-publish
  upload-firefox-store:
    needs: [build]
    name: Upload extension to Firefox Store
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3.7.0
        with:
          node-version: 16
      - uses: actions/download-artifact@v3
        with:
          name: tab-nine-firefox
      - run: zip release.zip ./* -r; mv release.zip ../release.zip; rm -rf *
      - uses: actions/checkout@v3.5.3
      - run: zip source.zip ./* -r; mv source.zip ../source.zip; rm -rf *
      - run: mv ../release.zip release.zip; mv ../source.zip source.zip
      - uses: yayuyokitano/firefox-addon@v0.0.6-alpha
        with:
          api_key: ${{ secrets.AMO_ISSUER }}
          api_secret: ${{ secrets.AMO_SECRET }}
          guid: "{${{ secrets.AMO_EXTENSION_ID }}}"
          xpi_path: release.zip
          src_path: source.zip
